INSERT INTO GENEROS (NOMBRE) VALUES('Accion');
INSERT INTO GENEROS (NOMBRE) VALUES('Comedia Ochentera');
INSERT INTO GENEROS (NOMBRE) VALUES('Terror');
INSERT INTO GENEROS (NOMBRE) VALUES('RoRo');
INSERT INTO GENEROS (NOMBRE) VALUES('Ficcion');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Jack Nicholson', 'https://www.purotip.com/wp-content/uploads/2012/04/jack-nicholson-0.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Tom Hanks', 'https://www.purotip.com/wp-content/uploads/2012/04/tomhanks.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Johnny Depp', 'https://www.purotip.com/wp-content/uploads/2012/04/jhonnydeep.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Anthony Hopkins', 'https://www.purotip.com/wp-content/uploads/2012/04/anthonyhopkins.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Denzel Washington', 'https://www.purotip.com/wp-content/uploads/2012/04/denzelwashington.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Leonardo Dicaprio', 'https://www.purotip.com/wp-content/uploads/2012/04/leonardo-dicaprio1.jpg');
