INSERT INTO GENEROS (NOMBRE) VALUES('Accion');
INSERT INTO GENEROS (NOMBRE) VALUES('Comedia Ochentera');
INSERT INTO GENEROS (NOMBRE) VALUES('Terror');
INSERT INTO GENEROS (NOMBRE) VALUES('RoRo');
INSERT INTO GENEROS (NOMBRE) VALUES('Ficcion');